from __future__ import annotations


MAG7_TICKERS = (
    "AAPL",
    "AMZN",
    "GOOG",
    "GOOGL",
    "META",
    "MSFT",
    "NVDA",
    "TSLA",
)


QQQ_CONSTITUENTS = (
    "AAPL",
    "ABNB",
    "ADBE",
    "ADI",
    "ADP",
    "ADSK",
    "AEP",
    "ALNY",
    "AMAT",
    "AMD",
    "AMGN",
    "AMZN",
    "APP",
    "ARM",
    "ASML",
    "AVGO",
    "AXON",
    "BKNG",
    "BKR",
    "CCEP",
    "CDNS",
    "CEG",
    "CHTR",
    "CMCSA",
    "COST",
    "CPRT",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTSH",
    "DASH",
    "DDOG",
    "DXCM",
    "EA",
    "EXC",
    "FANG",
    "FAST",
    "FER",
    "FTNT",
    "GEHC",
    "GILD",
    "GOOG",
    "GOOGL",
    "HON",
    "IDXX",
    "INSM",
    "INTC",
    "INTU",
    "ISRG",
    "KDP",
    "KHC",
    "KLAC",
    "LIN",
    "LRCX",
    "MAR",
    "MCHP",
    "MDLZ",
    "MELI",
    "META",
    "MNST",
    "MPWR",
    "MRVL",
    "MSFT",
    "MSTR",
    "MU",
    "NFLX",
    "NVDA",
    "NXPI",
    "ODFL",
    "ORLY",
    "PANW",
    "PAYX",
    "PCAR",
    "PDD",
    "PEP",
    "PLTR",
    "PYPL",
    "QCOM",
    "REGN",
    "ROP",
    "ROST",
    "SBUX",
    "SHOP",
    "SNPS",
    "STX",
    "TEAM",
    "TMUS",
    "TRI",
    "TSLA",
    "TTWO",
    "TXN",
    "VRSK",
    "VRTX",
    "WBD",
    "WDAY",
    "WDC",
    "WMT",
    "XEL",
    "ZS",
)


UNIVERSE_CONFIG = {
    "mag7": {
        "label": "Mag 7 + Alphabet Share Classes",
        "description": "Core mega-cap leadership basket used for quick swing checks.",
        "members": set(MAG7_TICKERS),
    },
    "qqq": {
        "label": "QQQ Constituents",
        "description": "Nasdaq-100 companies currently tracked by Invesco QQQ.",
        "members": set(QQQ_CONSTITUENTS),
    },
    "market": {
        "label": "Top 500 Liquid U.S. Stocks",
        "description": "Top 500 liquid U.S. common stocks from a broader dollar-volume universe, with price and average-volume quality filters.",
        "members": None,
    },
}
